#!/usr/bin/env python

if __name__ == '__main__':
    from argparse import ArgumentParser
    P = ArgumentParser(description="Plot and analyse a spectrum.")
    P.add_argument('filename', nargs='+', help='One or more spectrum filenames.')
    args = P.parse_args()

    import sys
    import numpy as np
    from plotspec.plotspec_util import main

    np.seterr(divide='ignore', invalid='ignore')

    sys.exit(main(args))
