#!/usr/bin/env python

if __name__ == '__main__':
    from argparse import ArgumentParser
    P = ArgumentParser(description="Velocity plot for a spectrum. Requires a configuration file plot.cfg.")
    P.add_argument('filename', help='Spectrum filename.')
    args = P.parse_args()

    import sys
    from plotspec.plotvel_util import main
    sys.exit(main(args))
